language: node_js
node_js: 12.7.0

jobs:
  include:
    - stage: quality
    - script:
        - yarn
        - yarn lint
      name: 'Lint'
    - script:
        - yarn
        - yarn build
      name: 'Build'

    - stage: deploy
      name: 'Publish Component Set'
      if: branch IN (master, acceptance, edge) AND type != pull_request
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - yarn
        script:
          - yarn build && yarn bundle && yarn upload
        on:
          all_branches: true
