language: node_js
node_js: 14.2.0

jobs:
  include:
    - stage: linter
      script:
        - commitlint --from $(git rev-parse --short HEAD^1) --to $(git rev-parse --short HEAD^2)
      if: type = pull_request
      name: 'Commit lint'
    - script:
        - yarn
        - yarn lint
      name: 'Lint'
    - script:
        - yarn
        - yarn bundle
        - yarn build
      name: 'Build'

    - stage: deploy_test_environment
      name: 'Publish Component Set on test environments'
      if: branch IN (edge) AND type != pull_request
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - yarn
        script:
          - yarn build && yarn bundle && yarn upload
        on:
          all_branches: true

    - stage: deploy
      name: 'Publish Component Set'
      if: branch IN (acceptance, master) AND type != pull_request
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - yarn
        script:
          - yarn build && yarn bundle && yarn upload && npx semantic-release
        on:
          all_branches: true
